version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "RestfulAPI"
s3_bucket = "aws-sam.functions"
s3_prefix = "cloudFormationStack-RestfulAPI"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
